import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { AiVoiceService } from '../../services/ai-voice.service';

interface Report {
  id: string;
  title: string;
  category: 'Compliance' | 'Risk Assessment' | 'Client Onboarding' | 'Audit';
  generatedDate: string;
  generatedBy: string;
  format: 'PDF' | 'Excel' | 'CSV';
  status: 'Ready' | 'Generating';
}

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, RouterLinkActive],
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.scss']
})
export class ReportsComponent implements OnInit {
  currentUser = 'Admin User';
  searchQuery: string = '';
  selectedCategory: string = 'All';

  reports: Report[] = [
    { id: 'RPT-001', title: 'Monthly KYC Compliance Overview', category: 'Compliance', generatedDate: '20 May 2026', generatedBy: 'System Admin', format: 'PDF', status: 'Ready' },
    { id: 'RPT-002', title: 'High-Risk Client Summary', category: 'Risk Assessment', generatedDate: '18 May 2026', generatedBy: 'Risk Manager', format: 'Excel', status: 'Ready' },
    { id: 'RPT-003', title: 'Onboarding Turnaround Time (TAT)', category: 'Client Onboarding', generatedDate: '15 May 2026', generatedBy: 'Operations Lead', format: 'PDF', status: 'Ready' },
    { id: 'RPT-004', title: 'Q1 Audit Trail & Exception Log', category: 'Audit', generatedDate: '10 May 2026', generatedBy: 'Internal Auditor', format: 'CSV', status: 'Ready' },
    { id: 'RPT-005', title: 'Expired Documents Audit', category: 'Compliance', generatedDate: '05 May 2026', generatedBy: 'Compliance Officer', format: 'PDF', status: 'Ready' }
  ];

  constructor(
    private router: Router,
    public voiceService: AiVoiceService
  ) {}

  ngOnInit(): void {
    const storedUser = localStorage.getItem('user');
    if (storedUser) {
      try {
        const parsed = JSON.parse(storedUser);
        if (parsed.username) this.currentUser = parsed.username;
      } catch (e) {}
    }
  }

  get filteredReports(): Report[] {
    return this.reports.filter(rpt => {
      const matchesSearch = !this.searchQuery ||
        rpt.title.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        rpt.id.toLowerCase().includes(this.searchQuery.toLowerCase());

      const matchesCategory = this.selectedCategory === 'All' || rpt.category === this.selectedCategory;

      return matchesSearch && matchesCategory;
    });
  }

  downloadReport(report: Report) {
    const fileContent = `==================================================
EXPORTED REPORT: ${report.title.toUpperCase()}
==================================================
Report ID      : ${report.id}
Category       : ${report.category}
Generated Date : ${report.generatedDate}
Generated By   : ${report.generatedBy}
Format         : ${report.format}
==================================================
Confidential - For Internal Use Only
`;

    const mimeType = report.format === 'CSV' ? 'text/csv' : 'text/plain';
    const blob = new Blob([fileContent], { type: `${mimeType};charset=utf-8` });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `${report.id}_${report.title.replace(/\s+/g, '_')}.${report.format.toLowerCase()}`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
  }

  generateNewReport() {
    const newReport: Report = {
      id: `RPT-00${this.reports.length + 1}`,
      title: `Ad-hoc KYC Summary (${new Date().toLocaleDateString()})`,
      category: 'Compliance',
      generatedDate: '22 Jul 2026',
      generatedBy: this.currentUser,
      format: 'PDF',
      status: 'Ready'
    };
    this.reports.unshift(newReport);
  }

  logout() {
    localStorage.removeItem('user');
    this.router.navigate(['/login']);
  }
}
