package com.dbtitan.controller;

import com.dbtitan.entity.ClientEntity;
import com.dbtitan.entity.DocumentEntity;
import com.dbtitan.entity.ReportEntity;
import com.dbtitan.repository.ClientRepository;
import com.dbtitan.repository.DocumentRepository;
import com.dbtitan.repository.ReportRepository;
import lombok.RequiredArgsConstructor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@RestController
@RequestMapping("/api/reports")
@CrossOrigin(origins = "http://localhost:4200")
@RequiredArgsConstructor
public class ReportController {

    private final ReportRepository reportRepository;
    private final ClientRepository clientRepository;
    private final DocumentRepository documentRepository;

    /**
     * GET /api/reports
     * Fetch all report metadata stored in PostgreSQL
     */
    @GetMapping
    public ResponseEntity<List<ReportEntity>> getAllReports() {
        return ResponseEntity.ok(reportRepository.findAll());
    }

    /**
     * POST /api/reports/generate-wizard
     * Generates a new report entry in DB for a specific client and creates the PDF.
     */
    @PostMapping("/generate-wizard")
    public ResponseEntity<ReportEntity> createWizardReport(
            @RequestParam("clientId") String clientId,
            @RequestParam(value = "generatedBy", defaultValue = "Admin User") String generatedBy
    ) {
        ClientEntity client = clientRepository.findByClientId(clientId).orElse(null);

        if (client == null) {
            return ResponseEntity.badRequest().build();
        }

        long count = reportRepository.count() + 1;
        String newReportId = "RPT-" + String.format("%03d", count);

        ReportEntity newReport = ReportEntity.builder()
                .reportId(newReportId)
                .title("KYC Audit & Relationship Report - " + client.getClientName())
                .category("Compliance")
                .generatedDate(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy")))
                .generatedBy(generatedBy)
                .format("PDF")
                .status("Ready")
                .client(client) // Foreign key relation to ClientEntity
                .createdAt(LocalDateTime.now())
                .build();

        ReportEntity saved = reportRepository.save(newReport);
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    /**
     * GET /api/reports/download/{reportId}
     * Dynamic PDF report creation fetching real DB records
     */
    @GetMapping("/download/{reportId}")
    public ResponseEntity<byte[]> downloadReport(@PathVariable String reportId) throws IOException {
        ReportEntity report = reportRepository.findByReportId(reportId).orElse(null);

        ClientEntity client = report != null ? report.getClient() : null;
        List<DocumentEntity> docs = client != null ? documentRepository.findByClient(client) : documentRepository.findAll();

        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream cs = new PDPageContentStream(document, page)) {
                PDType1Font boldFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
                PDType1Font regularFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

                cs.beginText();
                cs.setFont(boldFont, 18);
                cs.newLineAtOffset(50, 750);
                cs.showText("KYC CLM - " + (report != null ? report.getTitle() : "Compliance Report"));
                cs.endText();

                cs.moveTo(50, 735);
                cs.lineTo(550, 735);
                cs.stroke();

                cs.beginText();
                cs.setFont(regularFont, 11);
                cs.setLeading(18);
                cs.newLineAtOffset(50, 700);

                cs.showText("Report Reference ID : " + reportId);
                cs.newLine();
                cs.showText("Export Timestamp    : " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy, HH:mm:ss")));
                cs.newLine();
                cs.showText("Generated By        : " + (report != null ? report.getGeneratedBy() : "System Admin"));
                cs.newLine();
                cs.newLine();

                if (client != null) {
                    cs.setFont(boldFont, 13);
                    cs.showText("Client Target Details:");
                    cs.newLine();
                    cs.setFont(regularFont, 10);
                    cs.showText("• Name: " + client.getClientName() + " (ID: " + client.getClientId() + ")");
                    cs.newLine();
                    cs.showText("• Type: " + client.getClientType() + " | Risk Rating: " + client.getRiskRating());
                    cs.newLine();
                    cs.showText("• Status: " + client.getStatus() + " | Onboarded: " + client.getOnboardedOn());
                    cs.newLine();
                    cs.newLine();
                }

                cs.setFont(boldFont, 13);
                cs.showText("Associated Documents (" + docs.size() + " Found):");
                cs.newLine();

                cs.setFont(regularFont, 10);
                if (docs.isEmpty()) {
                    cs.showText("No uploaded documents linked with this entity.");
                    cs.newLine();
                } else {
                    for (DocumentEntity d : docs) {
                        cs.showText("• " + d.getDocumentName() + " (" + d.getDocumentId() + ") - Status: " + d.getStatus());
                        cs.newLine();
                    }
                }

                cs.newLine();
                cs.setFont(boldFont, 9);
                cs.showText("--- End of Dynamic Database Report Export ---");
                cs.endText();
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            document.save(baos);

            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + reportId + "_Report.pdf\"")
                    .contentType(MediaType.APPLICATION_PDF)
                    .body(baos.toByteArray());
        }
    }
}